### ISSUE TITLE
Support for battery level as attribute

### ISSUE THREAD

**Issue by royto** [cbulock/lovelace-battery-entity#10]
For some entities, battery level is an attribute of an entity. 

![image](https://user-images.githubusercontent.com/6990995/65423142-a2909600-de08-11e9-9e4c-e219d024a5dc.png)

Please add support for attributes.
 
```yaml
- type: custom:battery-entity
  entity: sensor.front_door_lock_battery
  attribute: battery_level
```
