### ISSUE TITLE
UI doesn't reflect the battery level change in real time

### ISSUE THREAD

**Issue by pmazz** [cbulock/lovelace-battery-entity#22]
Hi, thanks for the component.

It looks like the UI does not reflect the battery state change in real time, but instead a page reload is needed.

I've placed in my lovelace the following:
``` yaml
- entity: sensor.cellphone_batt
  name: sensor.cellphone_batt (standard)
- entity: sensor.cellphone_batt
  name: sensor.cellphone_batt (battery-entity)
  type: custom:battery-entity
```

This is the result:
![GIF 10-03-2020 07-58-45](https://user-images.githubusercontent.com/44721151/76287623-2e0dbe80-62a5-11ea-83c6-7a7bb2f85e8b.gif)

Any clue ?
