### ISSUE TITLE
Add support for usage in Auto Entities card

### ISSUE THREAD

**Issue by sibbl** [cbulock/lovelace-battery-entity#23]
I'd like to use the card in the [auto-entities](https://github.com/thomasloven/lovelace-auto-entities) lovelace card using the following config:

```
card:
  title: Low Batteries
  type:  'custom:battery-entity'
filter:
  include:
    - attributes:
        battery: < 30
    - attributes:
        battery_level: < 30
show_empty: false
type: 'custom:auto-entities'
```

Unfortunately it renders no card at all as `this.stateObj` is `null` on the first render (at least).

**Comment by oxan** [comment]
This card only replaces the type for a single entity, not the whole card. So this is already possible, though you have to duplicate the config for each filter:
```
type: 'custom:auto-entities'
show_empty: false
card:
  title: Low Batteries
  type: entities
filter:
  include:
    - attributes:
        battery: < 30
      options:
        type: 'custom:battery-entity'
        # specify options for the battery-entity card here
    - attributes:
        battery_level: < 30
      options:
        type: 'custom:battery-entity'
        # specify options for the battery-entity card here
```
