### ISSUE TITLE
How to add multiple entities

### ISSUE THREAD

**Issue by Megachip** [cbulock/lovelace-battery-entity#24]
like the screenshot shown...

**Comment by andi-bar157** [comment]
create a card with the following on your lovelace:

```
type: entities
entities:
  - type: 'custom:battery-entity'
    entity: sensor.temperaturregler_battery_level
  - type: 'custom:battery-entity'
    entity: sensor.temperaturregler_6_battery_level
  - type: 'custom:battery-entity'
    entity: sensor.temperaturregler_5_battery_level
```
