### ISSUE TITLE
Use entities: to be compatible with auto-entities

### ISSUE THREAD

**Issue by kylerw** [cbulock/lovelace-battery-entity#6]
https://github.com/thomasloven/lovelace-auto-entities populates the `entities:` 

this may require making this it's own card rather than just an entity.

**Comment by kylerw** [comment]
Already supported using `options`

```
type: 'custom:auto-entities'
id: low_battery
show_empty: false
card:
  title: ❗ Low Battery
  type: entities
  show_header_toggle: false
filter:
  include:
    - domain: sensor
      entity_id: '*battery*'
      state: '<= 30'
      options:
        type: 'custom:battery-entity'
    - attributes:
        battery_level: '<= 30'
      domain: sensor
      options:
        type: 'custom:battery-entity'
    - attributes:
        battery: '<= 30'
      domain: sensor
      options:
        type: 'custom:battery-entity'
    - attributes:
        battery_level: '<= 30'
      domain: binary_sensor
      options:
        type: 'custom:battery-entity'
    - attributes:
        battery: '<= 30'
      domain: binary_sensor
      options:
        type: 'custom:battery-entity'


```
