### ISSUE TITLE
Help is needed. 

### ISSUE THREAD

**Issue by kgbfsb** [cbulock/lovelace-battery-entity#8]
Help is needed. I can’t set it up like yours. My battery icon is moving off.
![2019-08-12_181338](https://user-images.githubusercontent.com/20793078/62864386-6b20cb00-bd2d-11e9-8eee-a0c3d0dbe892.jpg)
How to fix it? And tell me how to output several sensors, like yours. You can see your lovelace code.

**Comment by drunkensouljah** [comment]
You could use it in a [Vertical Stack Card](https://www.home-assistant.io/lovelace/vertical-stack/).

Like this:
```yaml
type: vertical-stack
cards:
    - type: custom:battery-entity
      entity: sensor.iphonex_battery_level
    - type: custom:battery-entity
      entity: sensor.ipad_battery_level
```

Output:
![Output](https://d.pr/i/Bgq9cn+)
