### ISSUE TITLE
Feature Request: Support for HACS

### ISSUE THREAD

**Issue by carldebilly** [cbulock/lovelace-battery-entity#9]
It would be nice to be able to install this lovelace extension through HACS...

**Comment by royto** [comment]
More info [here](https://hacs.netlify.com/developer/general/)

**Comment by carldebilly** [comment]
@royto 404

**Comment by royto** [comment]
The URL has changed. Here the right one : https://hacs.netlify.com/docs/publish/start

**Comment by marine1988** [comment]
+1

**Comment by VooZ2** [comment]
+1

**Comment by janjbrand** [comment]
+1

**Comment by johntdyer** [comment]
100%

**Comment by fortepc** [comment]
+1

**Comment by jasonwilk** [comment]
yes, please

**Comment by chilicheech** [comment]
I just installed it via HACS and I'm getting this error:
```
Custom element doesn't exist: battery-entity.
type: 'custom:battery-entity'
entity: sensor.side_door_battery_level
```
This is how I defined the card:
```
entities:
  - type: 'custom:battery-entity'
    entity: sensor.side_door_battery_level
  - type: 'custom:battery-entity'
    entity: sensor.kids_battery_level
  - type: 'custom:battery-entity'
    entity: sensor.master_battery_level
show_header_toggle: false
title: batteries
type: entities
```

**Comment by jhanson999** [comment]
Try this:
  - type: module
    url: community_plugin/lovelace-battery-entity/battery-entity.js

**Comment by jhanson999** [comment]
Try this header:
```
resources:
  - type: module
    url: /community_plugin/lovelace-battery-entity/battery-entity.js

```
And like this for the card:

```
type: vertical-stack
title: Battery Levels
cards:
  - type: 'custom:battery-entity'
    entity: sensor.back_yard_door_7_battery_level   
  - type: 'custom:battery-entity'
     entity: sensor.basement_door_123_battery_level
```
